/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'DELL' at '09.08.16 4:53' with Gradle 2.5
 *
 * @author DELL, @date 09.08.16 4:53
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
